# Generated by Django 5.1.5 on 2025-04-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
