# Generated by Django 5.1.5 on 2025-02-02 10:59

import django.core.validators
import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.IntegerField(choices=[(1, 'IT SERVICES'), (2, 'Product Based'), (3, 'Finance'), (4, 'Sport')])),
                ('url', models.URLField(unique=True)),
                ('linkedin_url', models.URLField()),
                ('linkedin_company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, default='default-org.jpeg', null=True, upload_to='organization-avatars', validators=[django.core.validators.validate_image_file_extension])),
                ('knowledge', models.TextField(blank=True)),
                ('root_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_root_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=organization.models.create_organization_invite, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
