# Generated by Django 5.2 on 2025-06-16 18:35

import django.core.validators
import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter_location', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('employee_size', models.IntegerField(choices=[(1, '1-10'), (2, '100-100'), (3, '100-500'), (4, '500-1000'), (5, '1000+')])),
                ('name', models.CharField(max_length=100)),
                ('industry', models.IntegerField(choices=[(1, 'IT SERVICES'), (2, 'Product Based'), (3, 'Finance'), (4, 'Sport')])),
                ('assistant_id', models.CharField(blank=True, max_length=40)),
                ('url', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin_url', models.URLField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, default='default-org.jpeg', null=True, upload_to='organization-avatars', validators=[django.core.validators.validate_image_file_extension])),
                ('root_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_root_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=organization.models.create_organization_invite, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
