# Generated by Django 5.2 on 2025-10-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='assistant_id',
        ),
    ]
