# Generated by Django 5.1.5 on 2025-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='twitter_access_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_refresh_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
