# Generated by Django 5.2 on 2025-10-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_assistant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.IntegerField(choices=[(1, 'IT SERVICES'), (2, 'Product Based'), (3, 'Finance'), (4, 'Sport'), (5, 'Healthcare'), (6, 'Automobile'), (7, 'Non-Profit'), (8, 'Public-Sector'), (9, 'Retail'), (10, 'Hospitality'), (11, 'Business'), (12, 'Others')]),
        ),
    ]
