# Generated by Django 5.1.5 on 2025-02-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_twitter_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='linkedin_company_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='twitter_access_token',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='twitter_refresh_token',
        ),
        migrations.AlterField(
            model_name='organization',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
