# Generated by Django 5.1.5 on 2025-02-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_organization_knowledge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='url',
        ),
    ]
