# Generated by Django 5.1.5 on 2025-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_organization_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='avatar',
        ),
    ]
