# Generated by Django 5.1.5 on 2025-02-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_organization_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('IT SERVICES', 'IT SERVICES'), ('Product Based', 'Product Based'), ('Finance', 'Finance'), ('Sport', 'Sport')], max_length=100),
        ),
    ]
