# Generated by Django 5.1.5 on 2025-03-27 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_assistant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(default='XYZ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='avatar',
            field=models.ImageField(blank=True, default='default-org.jpeg', null=True, upload_to='organization-avatars', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='organization',
            name='employee_size',
            field=models.IntegerField(choices=[(1, '1-10'), (2, '100-100'), (3, '100-500'), (4, '500-1000'), (5, '1000+')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarter_location',
            field=models.CharField(default='EC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.IntegerField(choices=[(1, 'IT SERVICES'), (2, 'Product Based'), (3, 'Finance'), (4, 'Sport')]),
        ),
    ]
