# Generated by Django 5.1.5 on 2025-03-27 07:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_organization_about_organization_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='Candidates-Resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('resume_data', models.JSONField(blank=True, null=True)),
                ('willing_to_relocate', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('employment_type_preferences', models.JSONField(default=list)),
                ('work_mode_preferences', models.JSONField(default=list)),
                ('has_workvisa', models.BooleanField(default=False)),
                ('expected_salary_range', models.CharField(blank=True, max_length=20, null=True)),
                ('video_pitch_url', models.FileField(blank=True, null=True, upload_to='Candidates-VideoPitches', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'wmv', 'avi', 'avchd', 'flv', 'f4v', 'swf', 'mkv'])])),
                ('is_available', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ['organization', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField()),
                ('section', models.TextField(blank=True, null=True)),
                ('selected_text', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(max_length=100)),
                ('note_file', models.FileField(blank=True, null=True, upload_to='Notes-File', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpeg', 'png', 'svg'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidateprofile')),
            ],
        ),
    ]
