# Generated by Django 5.2 on 2025-10-29 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('organization', '0003_alter_organization_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['is_available', 'parsing_status'], name='candidates__is_avai_2939fb_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['has_workvisa'], name='candidates__has_wor_57edba_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['slug'], name='candidates__slug_98b3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['user'], name='candidates__user_id_61b599_idx'),
        ),
    ]
