# Generated by Django 5.1.5 on 2025-03-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateconvo_candidateprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='assistant_id',
            field=models.CharField(blank=True, help_text='OpenAI Assistant ID for personalized job search', max_length=255, null=True),
        ),
    ]
