# Generated by Django 5.1.5 on 2025-03-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidateprofile_assistant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='employment_type_preferences',
            field=models.JSONField(default=list, help_text="Array of employment types like ['Full-time', 'Part-time', 'Contract']"),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='work_mode_preferences',
            field=models.JSONField(default=list, help_text="Array of work modes like ['Remote', 'On-site', 'Hybrid']"),
        ),
    ]
