# Generated by Django 5.1.5 on 2025-04-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidateprofile_employment_type_preferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprompt',
            name='convo',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='assistant_id',
        ),
        migrations.DeleteModel(
            name='CandidateConvo',
        ),
        migrations.DeleteModel(
            name='CandidatePrompt',
        ),
    ]
