# Generated by Django 5.1.5 on 2025-04-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidateprofile_accommodation_needs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='disclosure_preference',
            field=models.CharField(choices=[('DURING_APPLICATION', 'DURING_APPLICATION'), ('DURING_INTERVIEW', 'DURING_INTERVIEW'), ('AFTER_JOB_OFFER', 'AFTER_JOB_OFFER'), ('AFTER_STARTING_WORK', 'AFTER_STARTING_WORK'), ('NOT_APPLICABLE', 'NOT_APPLICABLE')], default='DURING_APPLICATION', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='accommodation_needs',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('PREFER_TO_DISCUSS_LATER', 'PREFER_TO_DISCUSS_LATER')], max_length=100),
        ),
    ]
