# Generated by Django 5.1.5 on 2025-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_candidateprofile_disclosure_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='parsing_status',
            field=models.CharField(choices=[('not_parsed', 'Not Parsed'), ('parsing', 'Parsing in Progress'), ('parsed', 'Parsed Successfully'), ('failed', 'Parsing Failed')], default='not_parsed', max_length=20),
        ),
    ]
