# Generated by Django 5.1.5 on 2025-02-03 10:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='Candidates-Resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobpost')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
