# Generated by Django 5.2 on 2025-10-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_jobpost_ranking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='ranking_status',
            field=models.CharField(choices=[('not_ranked', 'Not Ranked'), ('ranking', 'Ranking in Progress'), ('ranked', 'Ranked Successfully'), ('failed', 'Ranking Failed')], default='not_ranked', max_length=20),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='ranking_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255, null=True),
        ),
    ]
