# Generated by Django 5.1.5 on 2025-02-16 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_applicant_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='Candidates-Resume', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('resume_data', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('current_location', models.CharField(max_length=200)),
                ('linkedin_url', models.URLField(unique=True)),
                ('willing_to_relocate', models.BooleanField(default=True)),
                ('employment_type_preference', models.JSONField(default=list)),
                ('work_mode_preference', models.JSONField(default=list)),
                ('preferred_job_titles', models.JSONField(default=list)),
                ('preferred_industries', models.JSONField(default=list)),
                ('visa_work_auth_details', models.JSONField(blank=True, default=list)),
                ('min_expected_salary', models.CharField(max_length=20)),
                ('max_expected_salary', models.CharField(max_length=20)),
                ('availability_to_start', models.CharField(max_length=100)),
                ('github_url', models.URLField(unique=True)),
                ('video_pitch_url', models.FileField(upload_to='Candidates-VideoPitches', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'wmv', 'avi', 'avchd', 'flv', 'f4v', 'swf', 'mkv'])])),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
