# Generated by Django 5.2 on 2025-10-29 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_jobpost_ranking_status_jobpost_ranking_task_id'),
        ('organization', '0003_alter_organization_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['organization', 'created_at'], name='main_jobpos_organiz_6a0da8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['ranking_status'], name='main_jobpos_ranking_b12969_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['visa_required'], name='main_jobpos_visa_re_594c40_idx'),
        ),
    ]
