# Generated by Django 5.1.5 on 2025-02-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apicredentials_blocknote_channel_convo_prompt_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.IntegerField(choices=[(1, 'WorkDay')]),
        ),
    ]
