# Generated by Django 5.1.5 on 2025-02-20 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_candidateprofile_profile_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Candidate-Photo', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
