# Generated by Django 5.1.5 on 2025-02-28 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_skills_jobpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'Skills', 'verbose_name_plural': 'Skills'},
        ),
    ]
