# Generated by Django 5.1.5 on 2025-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.IntegerField(choices=[(1, 'WorkDay'), (2, 'Bamboo'), (3, 'Zoho')]),
        ),
    ]
