# Generated by Django 5.1.5 on 2025-03-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_channel_channel_type'),
        ('organization', '0006_alter_organization_industry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('organization', 'channel_type')},
        ),
    ]
