# Generated by Django 5.1.5 on 2025-03-23 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_channel_unique_together'),
        ('organization', '0007_organization_assistant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['organization', 'id']},
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='employment_type_preference',
            new_name='employment_type_preferences',
        ),
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='preferred_industries',
            new_name='work_mode_preferences',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='availability_to_start',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='max_expected_salary',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='min_expected_salary',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='preferred_job_titles',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='profile_avatar',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='visa_work_auth_details',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='work_mode_preference',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_workvisa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='video_pitch_url',
            field=models.FileField(blank=True, null=True, upload_to='Candidates-VideoPitches', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'wmv', 'avi', 'avchd', 'flv', 'f4v', 'swf', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
