# Generated by Django 5.1.5 on 2025-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='estimated_salary',
            field=models.CharField(default='100k-120k', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
    ]
