# Generated by Django 5.1.5 on 2025-04-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_jobpost_matched_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='matched_candidates',
        ),
    ]
