# Generated by Django 5.1.5 on 2025-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_jobpost_matched_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='visa_required',
            field=models.BooleanField(default=False),
        ),
    ]
