# Generated by Django 5.1.5 on 2025-04-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_jobpost_visa_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='candidate_ranking_data',
            field=models.JSONField(blank=True, help_text='Stores candidate ranking results', null=True),
        ),
    ]
