# Generated by Django 5.1.5 on 2025-04-29 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_jobpost_candidate_ranking_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='blocknote',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='blocknote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='blocknote',
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='channel',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='convo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='convo',
        ),
        migrations.RemoveField(
            model_name='note',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='author',
        ),
        migrations.RemoveField(
            model_name='promptfeedback',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='promptfeedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='APICredentials',
        ),
        migrations.DeleteModel(
            name='BlockNote',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Convo',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='PromptFeedback',
        ),
    ]
